name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: "uzh"
        password: ${{ secrets.SSH_SCRET }}
        port: ${{ secrets.SERVER_PORT }} # опціонально, якщо ви не використовуєте стандартний порт 22
        script: |
        
          cd /home/uzh/uzh
          git pull uzh-oblik-back main
          pkill -f "python3 app.py" &
          wait
          nohup python3 app.py &
          
